"""add_copilot_index_jobs_table

Revision ID: 4f29dbca11b7
Revises: 015_copilot_tables
Create Date: 2025-12-25 17:46:57.021830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f29dbca11b7'
down_revision: Union[str, None] = '015_copilot_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_index_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_rebuild', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='copilot_index_job_status'), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('chunks_indexed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copilot_index_job_created', 'copilot_index_jobs', ['created_at'], unique=False)
    op.create_index('idx_copilot_index_job_status_created', 'copilot_index_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_copilot_index_job_tenant_status', 'copilot_index_jobs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_copilot_index_jobs_created_at'), 'copilot_index_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_index_jobs_status'), 'copilot_index_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_copilot_index_jobs_tenant_id'), 'copilot_index_jobs', ['tenant_id'], unique=False)
    op.create_table('indexing_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('policy_doc', 'resolved_exception', 'audit_event', 'tool_registry', 'playbook', name='indexing_source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_type', name='uq_indexing_state_tenant_source')
    )
    op.create_index('idx_indexing_state_tenant_source', 'indexing_state', ['tenant_id', 'source_type'], unique=False)
    op.alter_column('alert_config', 'threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_report_tenant_id'), 'audit_report', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_config_change_request_tenant_id'), 'config_change_request', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_copilot_doc_content_hash'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_doc_domain'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_doc_source_id'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_doc_source_type'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_doc_tenant_id'), table_name='copilot_documents')
    op.create_index('idx_copilot_doc_content_hash', 'copilot_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_copilot_documents_content_hash'), 'copilot_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_copilot_documents_domain'), 'copilot_documents', ['domain'], unique=False)
    op.create_index(op.f('ix_copilot_documents_source_id'), 'copilot_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_copilot_documents_source_type'), 'copilot_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_copilot_documents_tenant_id'), 'copilot_documents', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_copilot_msg_created_at'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_msg_session_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_msg_tenant_id'), table_name='copilot_messages')
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_messages_exception_id'), 'copilot_messages', ['exception_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_request_id'), 'copilot_messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_session_id'), 'copilot_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_copilot_messages_tenant_id'), 'copilot_messages', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_copilot_session_tenant_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_session_user_id'), table_name='copilot_sessions')
    op.create_index(op.f('ix_copilot_sessions_tenant_id'), 'copilot_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_copilot_sessions_user_id'), 'copilot_sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_dead_letter_events_event_id'), 'dead_letter_events', type_='unique')
    op.create_index(op.f('ix_dead_letter_events_status'), 'dead_letter_events', ['status'], unique=False)
    op.alter_column('domain_packs', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'deprecated', name='pack_status'),
               type_=sa.Enum('draft', 'active', 'deprecated', name='pack_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::pack_status"))
    op.create_index(op.f('ix_event_processing_status'), 'event_processing', ['status'], unique=False)
    op.alter_column('exception', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='exception_severity'),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='exception_severity', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('exception', 'status',
               existing_type=postgresql.ENUM('open', 'analyzing', 'resolved', 'escalated', name='exception_status'),
               type_=sa.Enum('open', 'analyzing', 'resolved', 'escalated', name='exception_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::exception_status"))
    op.alter_column('exception_event', 'actor_type',
               existing_type=postgresql.ENUM('agent', 'user', 'system', name='actor_type'),
               type_=sa.Enum('agent', 'user', 'system', name='actor_type', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_gov_audit_action'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_actor_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_correlation_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_created_at'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_domain'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_entity_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_entity_type'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_event_type'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_related_change_request_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_related_exception_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_request_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_gov_audit_tenant_id'), table_name='governance_audit_event')
    op.create_index(op.f('ix_governance_audit_event_action'), 'governance_audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_actor_id'), 'governance_audit_event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_correlation_id'), 'governance_audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_created_at'), 'governance_audit_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_domain'), 'governance_audit_event', ['domain'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_entity_id'), 'governance_audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_entity_type'), 'governance_audit_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_event_type'), 'governance_audit_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_related_change_request_id'), 'governance_audit_event', ['related_change_request_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_related_exception_id'), 'governance_audit_event', ['related_exception_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_request_id'), 'governance_audit_event', ['request_id'], unique=False)
    op.create_index(op.f('ix_governance_audit_event_tenant_id'), 'governance_audit_event', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pii_redaction_metadata_exception_id'), 'pii_redaction_metadata', ['exception_id'], unique=False)
    op.create_index(op.f('ix_pii_redaction_metadata_tenant_id'), 'pii_redaction_metadata', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_config_tenant_id'), 'rate_limit_config', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_usage_tenant_id'), 'rate_limit_usage', ['tenant_id'], unique=False)
    op.alter_column('tenant', 'status',
               existing_type=postgresql.ENUM('active', 'suspended', 'archived', name='tenant_status'),
               type_=sa.Enum('active', 'suspended', 'archived', name='tenant_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::tenant_status"))
    op.alter_column('tenant_packs', 'status',
               existing_type=postgresql.ENUM('draft', 'active', 'deprecated', name='pack_status'),
               type_=sa.Enum('draft', 'active', 'deprecated', name='pack_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::pack_status"))
    op.drop_index(op.f('idx_tool_enablement_tenant_tool'), table_name='tool_enablement')
    op.alter_column('tool_execution', 'status',
               existing_type=postgresql.ENUM('requested', 'running', 'succeeded', 'failed', name='tool_execution_status'),
               type_=sa.Enum('requested', 'running', 'succeeded', 'failed', name='tool_execution_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'requested'::tool_execution_status"))
    op.alter_column('tool_execution', 'requested_by_actor_type',
               existing_type=postgresql.ENUM('agent', 'user', 'system', name='actor_type'),
               type_=sa.Enum('agent', 'user', 'system', name='actor_type', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_usage_metric_tenant_id'), 'usage_metric', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_metric_tenant_id'), table_name='usage_metric')
    op.alter_column('tool_execution', 'requested_by_actor_type',
               existing_type=sa.Enum('agent', 'user', 'system', name='actor_type', native_enum=False),
               type_=postgresql.ENUM('agent', 'user', 'system', name='actor_type'),
               existing_nullable=False)
    op.alter_column('tool_execution', 'status',
               existing_type=sa.Enum('requested', 'running', 'succeeded', 'failed', name='tool_execution_status', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('requested', 'running', 'succeeded', 'failed', name='tool_execution_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'requested'::tool_execution_status"))
    op.create_index(op.f('idx_tool_enablement_tenant_tool'), 'tool_enablement', ['tenant_id', 'tool_id'], unique=True)
    op.alter_column('tenant_packs', 'status',
               existing_type=sa.Enum('draft', 'active', 'deprecated', name='pack_status', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('draft', 'active', 'deprecated', name='pack_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::pack_status"))
    op.alter_column('tenant', 'status',
               existing_type=sa.Enum('active', 'suspended', 'archived', name='tenant_status', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('active', 'suspended', 'archived', name='tenant_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::tenant_status"))
    op.drop_index(op.f('ix_rate_limit_usage_tenant_id'), table_name='rate_limit_usage')
    op.drop_index(op.f('ix_rate_limit_config_tenant_id'), table_name='rate_limit_config')
    op.drop_index(op.f('ix_pii_redaction_metadata_tenant_id'), table_name='pii_redaction_metadata')
    op.drop_index(op.f('ix_pii_redaction_metadata_exception_id'), table_name='pii_redaction_metadata')
    op.drop_index(op.f('ix_governance_audit_event_tenant_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_request_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_related_exception_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_related_change_request_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_event_type'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_entity_type'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_entity_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_domain'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_created_at'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_correlation_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_actor_id'), table_name='governance_audit_event')
    op.drop_index(op.f('ix_governance_audit_event_action'), table_name='governance_audit_event')
    op.create_index(op.f('ix_gov_audit_tenant_id'), 'governance_audit_event', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_request_id'), 'governance_audit_event', ['request_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_related_exception_id'), 'governance_audit_event', ['related_exception_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_related_change_request_id'), 'governance_audit_event', ['related_change_request_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_event_type'), 'governance_audit_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_gov_audit_entity_type'), 'governance_audit_event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_gov_audit_entity_id'), 'governance_audit_event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_domain'), 'governance_audit_event', ['domain'], unique=False)
    op.create_index(op.f('ix_gov_audit_created_at'), 'governance_audit_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_gov_audit_correlation_id'), 'governance_audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_actor_id'), 'governance_audit_event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_gov_audit_action'), 'governance_audit_event', ['action'], unique=False)
    op.alter_column('exception_event', 'actor_type',
               existing_type=sa.Enum('agent', 'user', 'system', name='actor_type', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('agent', 'user', 'system', name='actor_type'),
               existing_nullable=False)
    op.alter_column('exception', 'status',
               existing_type=sa.Enum('open', 'analyzing', 'resolved', 'escalated', name='exception_status', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('open', 'analyzing', 'resolved', 'escalated', name='exception_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::exception_status"))
    op.alter_column('exception', 'severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='exception_severity', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='exception_severity'),
               existing_nullable=False)
    op.drop_index(op.f('ix_event_processing_status'), table_name='event_processing')
    op.alter_column('domain_packs', 'status',
               existing_type=sa.Enum('draft', 'active', 'deprecated', name='pack_status', native_enum=False, create_constraint=True),
               type_=postgresql.ENUM('draft', 'active', 'deprecated', name='pack_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::pack_status"))
    op.drop_index(op.f('ix_dead_letter_events_status'), table_name='dead_letter_events')
    op.create_unique_constraint(op.f('uq_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'])
    op.drop_index(op.f('ix_copilot_sessions_user_id'), table_name='copilot_sessions')
    op.drop_index(op.f('ix_copilot_sessions_tenant_id'), table_name='copilot_sessions')
    op.create_index(op.f('ix_copilot_session_user_id'), 'copilot_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_copilot_session_tenant_id'), 'copilot_sessions', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_copilot_messages_tenant_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_session_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_request_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_exception_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.create_index(op.f('ix_copilot_msg_tenant_id'), 'copilot_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_copilot_msg_session_id'), 'copilot_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_copilot_msg_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_copilot_documents_tenant_id'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_documents_source_type'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_documents_source_id'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_documents_domain'), table_name='copilot_documents')
    op.drop_index(op.f('ix_copilot_documents_content_hash'), table_name='copilot_documents')
    op.drop_index('idx_copilot_doc_content_hash', table_name='copilot_documents')
    op.create_index(op.f('ix_copilot_doc_tenant_id'), 'copilot_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_copilot_doc_source_type'), 'copilot_documents', ['source_type'], unique=False)
    op.create_index(op.f('ix_copilot_doc_source_id'), 'copilot_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_copilot_doc_domain'), 'copilot_documents', ['domain'], unique=False)
    op.create_index(op.f('ix_copilot_doc_content_hash'), 'copilot_documents', ['content_hash'], unique=False)
    op.drop_index(op.f('ix_config_change_request_tenant_id'), table_name='config_change_request')
    op.drop_index(op.f('ix_audit_report_tenant_id'), table_name='audit_report')
    op.alter_column('alert_config', 'threshold',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index('idx_indexing_state_tenant_source', table_name='indexing_state')
    op.drop_table('indexing_state')
    op.drop_index(op.f('ix_copilot_index_jobs_tenant_id'), table_name='copilot_index_jobs')
    op.drop_index(op.f('ix_copilot_index_jobs_status'), table_name='copilot_index_jobs')
    op.drop_index(op.f('ix_copilot_index_jobs_created_at'), table_name='copilot_index_jobs')
    op.drop_index('idx_copilot_index_job_tenant_status', table_name='copilot_index_jobs')
    op.drop_index('idx_copilot_index_job_status_created', table_name='copilot_index_jobs')
    op.drop_index('idx_copilot_index_job_created', table_name='copilot_index_jobs')
    op.drop_table('copilot_index_jobs')
    # ### end Alembic commands ###

