"""
Guardrail Recommendation API routes (P3-10).

Backend API for retrieving guardrail adjustment recommendations.
"""

import logging
from typing import Any, Optional

from fastapi import APIRouter, HTTPException, Query

from src.audit.logger import AuditLogger
from src.learning.guardrail_recommender import (
    GuardrailRecommender,
    GuardrailRecommenderError,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/learning/guardrail-recommendations", tags=["learning", "guardrails"])


# Global recommender instance
# In production, this would be injected via dependency injection
_guardrail_recommender: Optional[GuardrailRecommender] = None


def get_guardrail_recommender() -> GuardrailRecommender:
    """
    Get the global guardrail recommender instance.
    
    Returns:
        GuardrailRecommender instance
    """
    global _guardrail_recommender
    if _guardrail_recommender is None:
        _guardrail_recommender = GuardrailRecommender()
    return _guardrail_recommender


@router.get("")
async def get_guardrail_recommendations(
    tenant_id: str = Query(..., description="Tenant identifier"),
    domain: str = Query(..., description="Domain name identifier"),
    guardrail_id: Optional[str] = Query(None, description="Optional guardrail ID filter"),
) -> dict[str, Any]:
    """
    Get guardrail adjustment recommendations for a tenant and domain.
    
    Phase 3: Retrieves guardrail recommendations generated by GuardrailRecommender (P3-10).
    
    Query Parameters:
    - tenant_id: Tenant identifier (required)
    - domain: Domain name identifier (required)
    - guardrail_id: Optional guardrail ID to filter recommendations
    
    Returns:
    - JSON response with list of guardrail recommendations
    """
    try:
        recommender = get_guardrail_recommender()
        
        # Load recommendations
        recommendations = recommender.load_recommendations(tenant_id, domain)
        
        # Filter by guardrail_id if provided
        if guardrail_id:
            recommendations = [r for r in recommendations if r.guardrail_id == guardrail_id]
        
        # Convert to dict format
        recommendations_dict = [r.model_dump(by_alias=True, mode="json") for r in recommendations]
        
        # Log audit entry (get audit logger if available)
        try:
            from src.audit.logger import get_audit_logger
            audit_logger = get_audit_logger()
            if audit_logger:
                for rec in recommendations:
                    # Check if method exists before calling
                    if hasattr(audit_logger, "log_guardrail_recommendation_generated"):
                        audit_logger.log_guardrail_recommendation_generated(
                            tenant_id=tenant_id,
                            domain=domain,
                            recommendation_id=rec.guardrail_id,
                            guardrail_id=rec.guardrail_id,
                            recommendation_data=rec.model_dump(by_alias=True, mode="json"),
                        )
        except (ImportError, AttributeError):
            # Audit logging is optional, continue if not available
            pass
        
        return {
            "tenant_id": tenant_id,
            "domain": domain,
            "guardrail_id": guardrail_id,
            "recommendations": recommendations_dict,
            "count": len(recommendations_dict),
        }
    except GuardrailRecommenderError as e:
        logger.error(f"Guardrail recommender error: {e}")
        raise HTTPException(status_code=500, detail=str(e)) from e
    except Exception as e:
        logger.error(f"Unexpected error retrieving guardrail recommendations: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Internal server error") from e

